### ISSUE TITLE
ACRE is Being a Shit

### ISSUE THREAD

**Issue by SpazzMods** [DeathDeliveryCorps/Operations#150]
Please check the following boxes accordingly, then provide the information in the related category:
- [x] This is a bug report
- [ ] This is a mission request
- [ ] This is an addition to a current mission
- [ ] Other

If this is a bug report, please provide the following:
- [ ] Your RPT file from [here](https://community.bistudio.com/wiki/Crash_Files): https://gist.github.com/SpazzMods/f90529af0559f7a37a0b42ae366fec10
- [x] The mission this occured on: Altis Zeus
- [x] The *time* this occured, please be as accurate as possible: Midnight-1:30
- [x] A description of the bug: ACRE had completely stopped working, 148's were not communicating to 152's or 117's, distance/interference was not an issue LOS was made and issue persisted. 
- [x] What you were doing at the time: Trying to be JTAC

If this is a mission request, please provide the following:
- [ ] The map this is to be built on
- [ ] An overall plan for the mission, in objective format
- [ ] Some background detail as to why we're doing the mission
- [ ] What faction we're playing as, as well as related kits if possible

If this is an addition to a current mission:
- [ ] The mission name
- [ ] What needs to be added

**Comment by DahBlount** [comment]
Can confirm this is an issue. Woods and I were CAS and we could only receive small, incomplete snippets of the ground comms.

**Comment by Aselia** [comment]
https://gist.github.com/Aselia/c302f21e066ebd06b8236bfae9207f7d

My own RPT file of the previous OP. Hope this helps.

**Comment by SchwererKonigstiger** [comment]
Confirmed to be a local issue with player-end plugins.
Can't do anything about it currently.

Will keep the issue open and keep tracking.
More RPTs welcome.

**Comment by SchwererKonigstiger** [comment]
Fixed an issue with antenna direction, closing ticket.
