### ISSUE TITLE
Squad Respawn

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#155]
Make SQLs and Medics respawn points for players.

**Comment by SchwererKonigstiger** [comment]
Inside `initPlayerLocal.sqf`
Attempting to utilize the following:
`[west,sql1var] call BIS_fnc_addRespawnPosition;`


Should be JIP compatible, may require JIP flags.
needs to be tested.
In `description.ext`, `respawnOnStart = 1` must be present

**Comment by SchwererKonigstiger** [comment]
Respawn on vehicles as an MHQ is working via calling:
`[guerilla, vehiclename] call BIS_fnc_addRespawnPosition;`

**Comment by Eogos** [comment]
Now to be done in the new Zeus templates after server is fully operational again.
- [ ] Make TLs Spawn Points
- [ ] Add MH-6 LittleBird as MHQ
- [ ] Add Burnes' Foxhound as MHQ

**Comment by Eogos** [comment]
moving to issue #205
