### ISSUE TITLE
Strange Ace Issues with new Arma Update

### ISSUE THREAD

**Issue by SpazzMods** [DeathDeliveryCorps/Operations#169]
Please check the following boxes accordingly, then provide the information in the related category:
- [x] This is a bug report
- [ ] This is a mission request
- [ ] This is an addition to a current mission
- [ ] Other

If this is a bug report, please provide the following:
- [x] Your RPT file from [here](https://community.bistudio.com/wiki/Crash_Files)
Sherb: https://gist.github.com/SpazzMods/c34455a731443bad4d6b4a9035e8f82d
Moo: https://gist.github.com/anonymous/e3dc01756462036bae80c6fbf11e0fc7
Eogos: https://gist.github.com/Eogos/cb65cf102153c11ebc03784ef8dc6c01
- [x] The mission this occured on Tanoa Insurgent Warfare
- [x] The *time* this occured, please be as accurate as possible: 22:20 EST
- [x] A description of the bug: Insta crash with some form of Ace Errors
- [x] What you were doing at the time Shot while trying to fix a wheel

If this is a mission request, please provide the following:
- [ ] The map this is to be built on
- [ ] An overall plan for the mission, in objective format
- [ ] Some background detail as to why we're doing the mission
- [ ] What faction we're playing as, as well as related kits if possible

If this is an addition to a current mission:
- [ ] The mission name
- [ ] What needs to be added

**Comment by SchwererKonigstiger** [comment]
All issues isolated to clients.
