### ISSUE TITLE
E_OUTOFMEMORY Crash

### ISSUE THREAD

**Issue by DahBlount** [DeathDeliveryCorps/Operations#181]
RPT: http://pastebin.com/7RvKLNXn
This occurred on TIW at approximately 10:24PM Central Time.
Similar to previous crashes, the game ran out of virtual memory. However, it consumed more physical memory before crashing. Additionally, the game did not begin to drop in performance to extremely low fps, it just CTD directly from an 80 fps situation.
Before the crash occurred, Alasdhair and myself were attempting to remove the forces from an airfield so we could steal a Hatchback. I was sniping while Alasdhair was attempting to make a distraction and kill an APC. Alasdhair did not crash.

**Comment by SchwererKonigstiger** [comment]
Merged with #182 
Similar/Same issue.
