### ISSUE TITLE
2-5 FPS error

### ISSUE THREAD

**Issue by sdooW** [DeathDeliveryCorps/Operations#182]
Please check the following boxes accordingly, then provide the information in the related category:
- [X ] This is a bug report
- [ ] This is a mission request
- [ ] This is an addition to a current mission
- [ ] Other

If this is a bug report, please provide the following:
- [arma3 rpts.zip](https://github.com/DeathDeliveryCorps/Operations/files/689022/arma3.rpts.zip)
- Tanoa Insurgent Warfare
- between 10:30pm-11pm Central
- Frames just cut to 2-5 fps and never recovers. Constant lag is experienced.] A description of the bug
- I was just walking when it started this time. Other times it seems to start with firefights, or when absolutely nothing is pressed.

**Comment by SchwererKonigstiger** [comment]
```RPT: http://pastebin.com/7RvKLNXn
This occurred on TIW at approximately 10:24PM Central Time.
Similar to previous crashes, the game ran out of virtual memory. However, it consumed more physical memory before crashing. Additionally, the game did not begin to drop in performance to extremely low fps, it just CTD directly from an 80 fps situation.
Before the crash occurred, Alasdhair and myself were attempting to remove the forces from an airfield so we could steal a Hatchback. I was sniping while Alasdhair was attempting to make a distraction and kill an APC. Alasdhair did not crash.```
From #181

**Comment by Eogos** [comment]
TIW is no longer an active mission due to the removal of ALiVE
