### ISSUE TITLE
Patch Addition

### ISSUE THREAD

**Issue by BSherb** [DeathDeliveryCorps/Operations#184]
Please check the following boxes accordingly, then provide the information in the related category:
- [ ] This is a bug report
- [ ] This is a mission request
- [ ] This is an addition to a current mission
- [x] Other: add the Hole Stuffing Specialist Patch to Server [this thing](https://cdn.shopify.com/s/files/1/1151/9112/products/NURSE_large.PNG?v=1472250127)

**Comment by Eogos** [comment]
Already added via the WGW mod by Konig.
