### ISSUE TITLE
Alive Actions Re-Add

### ISSUE THREAD

**Issue by BSherb** [DeathDeliveryCorps/Operations#190]
Please check the following boxes accordingly, then provide the information in the related category:
- [ ] This is a bug report
- [ ] This is a mission request
- [x] This is an addition to a current mission
- [ ] Other

If this is an addition to a current mission:
- [x] The mission name: Templates
- [x] What needs to be added: Alive Actions so Grass can be turned off again

**Comment by Eogos** [comment]
ALiVE mod has been dropped from the modpack due to issues with the mod.
