### ISSUE TITLE
Zeus Template Redo

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#205]
- [ ] Build vehicle repair/rearm/refuel station/garage/bay
- [ ] Build helicopter landing pad(s)
- [ ] Build infantry "barracks" with arsenal(s)
- [ ] Add Zeus slots for Taihou
- [ ] Move ACRE modules over to CBA settings
- [ ] copy old shit over
- [ ] finish Issue #155 
- [ ] Re-Add OCAP console
- [ ] Make TLs mobile spawn points

**Comment by Eogos** [comment]
Don't forget to make one in VR so it can be easily copy pasted later

**Comment by SchwererKonigstiger** [comment]
Add:
- [ ] Foxhound MRAP as MHQ
- [ ] Little Bird (Vanilla) as MHQ
_These should not be respawnable_
