### ISSUE TITLE
General Zeus Maintenance

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#253]
- [x] Change Squad and Team lead unit type to NATO Combat Life Saver on all Zeus maps
- [x] Delete Zeus maps that are too small to be used outside of editor, such as desert island and desert
- [x] Check all maps for proper independent hostility and make sure they are hostile to both BLUFOR and REDFOR
- [x] Remove Apex dependency from all Zeus maps besides Tanoa (switch any apex items to their vanilla versions)
- [x] Make COS use proper civilians for the map (So Takistani civilians on Takistan, Russian civilians on Chernarus, etc.)
- [x] Decrease overall number of civilians for all town sizes but increase spawn distance

**Comment by Eogos** [comment]
- [ ] Remove Woods' Zeus slot from all maps

**Comment by Eogos** [comment]
- [ ] Add Zeus slots for Alasdhair and Spooky

**Comment by Eogos** [comment]
- [ ] Fix respawn marker on WW2 maps

**Comment by SchwererKonigstiger** [comment]
Bump and push. This should be done by the end of the month.

**Comment by Aselia** [comment]
Malden 2035 confirmed broken on hostility of INDFOR @BSherb @alasdhairm

**Comment by SchwererKonigstiger** [comment]
@operator-chan How much of this is done?

**Comment by operator-chan** [comment]
All the main ops Zeus maps are complete.
The only ones not completed are the iron front maps.

**Comment by Eogos** [comment]
He means for the COS shit. Other than COS everything checked is what is complete.

**Comment by SchwererKonigstiger** [comment]
This project is now late.
Please try to get it finished ASAP

**Comment by Oberstleutnant-Deutschland** [comment]
Hostility and spawn points fixed on IFA maps.
Zeus Slots for Nardy and Operator added to all Zeus maps.

**Comment by Eogos** [comment]
all tasks completed.
