### ISSUE TITLE
[DDC Ravage] Searching cars, boxes, seems to be broken.

### ISSUE THREAD

**Issue by Aleph-NullDDC** [DeathDeliveryCorps/Operations#316]
Searching wrecked cars, or boxes, or even the cabinets in the map always seems to turn up with nothing. No supplies, or gear, which you'd expect from the prompt being given. Not sure if this was intended or just requires some spawn rate tweaking.

**Comment by SchwererKonigstiger** [comment]
Increased Spawn Rate of Loot for searching... a lot.
