### ISSUE TITLE
Adjust Spawn Kits - Please Discuss

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#319]
Currently players spawn with the following equipment:

- Somewhat random selection of CUP/Vanilla Clothing (Uniform slot only)
- Makarov w/2 mags
- 2x Hi-White Glowsticks
- 1x Red Flare

**Comment by InfinitePondera** [comment]
Spawn with an empty canteen and a single food can

**Comment by SchwererKonigstiger** [comment]
Kits changed massively. Spawn in and check em out.
