### ISSUE TITLE
Safezone Guards

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#321]
I suggest you use CDF and their vehicles as guards for the safezones, it makes a lot of sense.

**Comment by InfinitePondera** [comment]
Make a system where CDF is likely to shoot you if you have killed Hero NPCs before

**Comment by Eogos** [comment]
that already happens Zyon, all players are BLUFOR and there are some friendly ai as well. If you kill them it marks you as a traitor and other BLUFOR AI will shoot you.

**Comment by SchwererKonigstiger** [comment]
Dohe
