### ISSUE TITLE
New players aren't spawning with a 152

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#327]
New people joining aren't spawning with a 152 anymore which is incredibly annoying and a pain in the ass considering then the only way to get any sort of radio is to kill a bandit and hope they have the vanilla radio and even then that only turns into a 343 so it's still completely useless for talking to everyone who already has their kits setup with a 152.

**Comment by SchwererKonigstiger** [comment]
Fixed in new ravage
