### ISSUE TITLE
replace Ravage radiation with Contamination Mod gas

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#329]
I suggest turning off the Ravage radiation and replacing it with the contamination mod's gas contamination zone. The radiation is just annoying and adds very little in the way of game play elements but I appreciate what it's trying to accomplish but failing. 

The contam mod could be used to place gas contam zones around areas in which better loot has a probability of spawning like Chernarus, Electro, the North West Airbase, etc. until you get a bit of gear, including a gas mask. Unlike radiation it wont slowly kill you over hours (and let's be honest you'll prob from zombies/bandits before radiation kills you) it'll actively start killing you as soon as you enter the lethal area, and if everyone has their warning devices on like they should it'll warn them before they enter a contam zone. 

Plus you can create different types of contamination if you want to get real complex with it. Some places may only need a gas mask while others may need you to find specific gear (like the CSAT body suits or something) in addition to the gas mask. You can also designate anything as a gas mask/protective suit so you could also make the Viper helmet a gas mask if you wanted.

**Comment by SchwererKonigstiger** [comment]
https://forums.bistudio.com/forums/topic/205673-jshk-contamination-area-mod/

**Comment by SchwererKonigstiger** [comment]
Permanently on hold due to no documentation.
