### ISSUE TITLE
Modpack Update 01/10/2017

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#339]
Confirmed Updates/To Install
- [x] CUP Dev
- [x] Enhanced Movement to Main Ops (Make it a framework)
- [x] ZEC - https://forums.bistudio.com/forums/topic/189096-zec-zeus-and-eden-templates-building-compositions/
- [x] Eden Enhanced
- [x] ASR AI
- [ ] CZC - https://forums.bistudio.com/forums/topic/170000-wip-custom-zeus-compositions/

Check for Updates:
- [x] Toadie's Weapons
- [x] Iron Front Update
- [x] Project Infinity

Discuss
- [x] POOK SAMS
- [ ] UCM - https://forums.bistudio.com/forums/topic/210728-ucm-utilities-construction-mod/
- [ ] JSHK - https://forums.bistudio.com/forums/topic/205673-jshk-contamination-area-mod/
- [ ] Add Support for JSRS - https://forums.bistudio.com/forums/topic/202118-jsrs-soundmod-5170807/
- [ ] HAFM Navy - https://forums.bistudio.com/forums/topic/209939-hafm-navy-v15-release/

**Comment by Eogos** [comment]
CZC - not being added due to addition of ZEC

UCM, JSHK, JSRS support, and HAFM still to be discussed
