### ISSUE TITLE
Make Chernogorsk interesting instead of a pain

### ISSUE THREAD

**Issue by InfinitePondera** [DeathDeliveryCorps/Operations#343]
Currently, Chernogorsk has nothing of interest, be it loot or other objectives, as well as being filled to the brim with trash, trees, blockades and crashed cars, making it very difficult to move around and costing a lot of FPS. My suggestion is to add a russian/chernarussian camp there with special vehicles and loot.

**Comment by Eogos** [comment]
Added a bunch of crates  on probability spawns and added a group of stranded friendly survivors/CDF held up in a makeshift safezone
