### ISSUE TITLE
Discuss: CRAMs on Zeus

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#35]
Should we leave the C-Rams on the Zeus Missions?
Yes or no?
If so, do we lock them permanently and make the occupants invulnerable?

**Comment by Eogos** [comment]
Might want to leave the crew vulnerable so that when we do stuff that we need them to not be there for we can still do it.

**Comment by SchwererKonigstiger** [comment]
No, because that's exactly why people are fucking with it. Oh hey, let's crawl underneath and shoot the crew out of the vehicle.

**Comment by Eogos** [comment]
That has never happened as far as I've seen, if we need them gone for a Zeus mission then we kill the crew from Zeus and delete the corpses. Then they are there again when we restart the mission. There really is no point in making that impossible.

**Comment by SchwererKonigstiger** [comment]
They crashed the server last night by doing that.
Either that, or we remove them entirely from the Zeus missions

**Comment by Eogos** [comment]
I would rather just remove them from the Zeus missions. The Zeus missions are supposed to be a completely black slate and by having them there it moves us away from that. If we need to have AA or something at the base then the person in Zeus can simply place one himself.
