### ISSUE TITLE
Build Player Kits

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#354]
Build Player Kits
(Will be updated w/slots)

- [ ] SQL
- [ ] Medic
- [ ] Enginner (?)
- [ ] Rifleman (Generic Base Role)
- [ ] Grenadier
- [ ] Light AT
- [ ] Dedicated AT
- [ ] MMG
- [ ] Ammo Bearer
- [ ] Autorifleman

**Comment by Oberstleutnant-Deutschland** [comment]
How should the squad compositions look like? Something like this?

SQL
Medic
Grenadier
MMG
Ammo Bearer
Light AT
Rifleman
Rifleman

&

SQL
Medic
Grenadier
Autorifleman
Dedicated AT
Engineer
Rifleman
Rifleman

**Comment by Aselia** [comment]
In my opinion,  that looks good, but maybe we should swap out one rifleman from the 2nd squad for another ammobearer to help supply the Dedicated AT?
