### ISSUE TITLE
Setup Convoy

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#359]
- [x] Convoy Vehicles
- [ ] Convoy Routing
- [ ] Convoy Scripting if needed

**Comment by Aselia** [comment]
Issues: Convoy will not continue pathing after dropping off passengers. Attempting to ignore passenger and simplely drive inside the base results in half the convoy entering and half going away to random places. Need to figure out a fix

**Comment by SchwererKonigstiger** [comment]
Needs to be rechecked.
