### ISSUE TITLE
Zeus Mission Changes

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#394]
- [x] Ground boxes on Altis Zeus
- [x] Unfuck Takistan Zeus in general
- [x] Make greenfor angry across the board
- [ ] Fix COS

**Comment by BSherb** [comment]
@SchwererKonigstiger Again, cos was added as instructed. Either look at it yourself or find someone who knows it.
Will fix the rest this weekend
