### ISSUE TITLE
Balance BLUFOR

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#416]
BLUFOR commander is still spawning way too many units at once.

Possible suggestions:

- [ ] Remove BLUFOR Commander Entirely
- [ ] Limit BFC to infantry only
- [ ] Nerf BFC's numbers again
- [ ] Limit operational scope of BFC

**Comment by Eogos** [comment]
You really dont need this, considering I was already going to try all of it

**Comment by SchwererKonigstiger** [comment]
Just leaving a ticket is helpful.
