### ISSUE TITLE
classnames of BLUFOR vehicles

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#430]
Please post or DM .txt files containing classnames of all BLUFOR vehicles (separated by type, aka Cars, armored, ship, etc.) for use on Altis Warfare in the factories.

**Comment by BSherb** [comment]
https://gist.github.com/BSherb/40ebf6f9baa500ce2942b0eb61fe40e2
https://gist.github.com/BSherb/db70b150ecc60f6ea0338ceaaaaaa637
https://gist.github.com/BSherb/c26e9c238a3711ebaa344873ca48a6bd
https://gist.github.com/BSherb/ee3a1716f33ab10fb4d935ed040353fb
https://gist.github.com/BSherb/13be6d29a4819d281ab75431e80a5522
