### ISSUE TITLE
SWOP Missions unloadable

### ISSUE THREAD

**Issue by SpookyNoodlesDDC** [DeathDeliveryCorps/Operations#457]
Pretty much every mission for SWOP (two) and even the vanilla missions are completely unloadable.

**Comment by SpookyNoodlesDDC** [comment]
Meaning that when I launch them, they stay on the loading screen, despite the bar being completely loaded, and they stay on that screen. I really don't want to time how long they'll take but if need be I will.

**Comment by Eogos** [comment]
@Oberstleutnant-Deutschland If you need further help on this consult @SherbWontFuckUpGitHub

**Comment by SpookyNoodlesDDC** [comment]
This is the fix for the loading issues, provided by the mod developers https://cdn.discordapp.com/attachments/365235739253932032/403727056959176705/Loading_Screen_Fix.zip
