### ISSUE TITLE
Player HP: Discussion

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#50]
Player HP is currently 2.5 (2.5 times base HP, or the HP of an AI)
Due to the issues below:
- Unmanagable number of wounds
- Too many large injuries that take too many bandages
- Expected removal of PAKs
- Broken legs

Player HP will have to be reduced to help manage this.

**Comment by Eogos** [comment]
How about we move it down to 1.0 HP for Saturday and tell them not to bring any PAKs to see how they handle at the lowered HP. If it goes horribly we can raise it up a bit, if it goes semi badly we know we just need to better train them on not getting shot/treating wounds/maneuvering and using cover etc, and if it goes fine then we know that 1.0 is fine.

**Comment by SchwererKonigstiger** [comment]
Possibly get it down Saturday morning for a test run.
