### ISSUE TITLE
Re-add Creation Factory

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#74]
- [ ] Add Creation Factory to Template Zeus
- [ ] Add Creation Factory to Altis Zeus
- [ ] Add Creation Factory to Tanoa Zeus
- [ ] Add Creation Factory to Stratis Zeus
- [ ] Add Creation Factory to Bystrica Zeus
- [ ] Add Creation Factory to Chernarus Zeus
- [ ] Add Creation Factory to Everon Zeus
- [ ] Add Creation Factory to Malden Zeus
- [ ] Add Creation Factory to Nogava Zeus
- [ ] Add Creation Factory to Sahrani Zeus
- [ ] Add Creation Factory to Takistan Zeus

**Comment by SchwererKonigstiger** [comment]
Remaking Issue...
