### ISSUE TITLE
Spawn DM prevention

### ISSUE THREAD

**Issue by rwindas** [DeathDeliveryCorps/Operations#98]
Please check the following boxes accordingly, then provide the information in the related category:
- [ ] This is a bug report
- [ ] This is a mission request
- [ ] This is an addition to a current mission
- [x] Other

If this is a bug report, please provide the following:
- [ ] Your RPT file from [here](https://community.bistudio.com/wiki/Crash_Files)
- [ ] The mission this occured on
- [ ] The *time* this occured, please be as accurate as possible
- [ ] A description of the bug
- [ ] What you were doing at the time

If this is a mission request, please provide the following:
- [ ] The map this is to be built on
- [ ] An overall plan for the mission, in objective format
- [ ] Some background detail as to why we're doing the mission
- [ ] What faction we're playing as, as well as related kits if possible

If this is an addition to a current mission:
- [ ] The mission name
- [ ] What needs to be added

**Comment by SchwererKonigstiger** [comment]
Closing issue - not enough information.
