### ISSUE TITLE
UGV Vehicles at Spawn

### ISSUE THREAD

**Issue by SpazzMods** [DeathDeliveryCorps/Operations#99]
Please check the following boxes accordingly, then provide the information in the related category:
- [ ] This is a bug report
- [ ] This is a mission request
- [x] This is an addition to a current mission
- [ ] Other

If this is a bug report, please provide the following:
- [ ] Your RPT file from [here](https://community.bistudio.com/wiki/Crash_Files)
- [ ] The mission this occured on
- [ ] The *time* this occured, please be as accurate as possible
- [ ] A description of the bug
- [ ] What you were doing at the time

If this is a mission request, please provide the following:
- [ ] The map this is to be built on
- [ ] An overall plan for the mission, in objective format
- [ ] Some background detail as to why we're doing the mission
- [ ] What faction we're playing as, as well as related kits if possible

If this is an addition to a current mission:
- [x] The mission name: Altis War Map
- [x] What needs to be added: UGV Vehicles for UAV Operators (Armed and Unarmed)

**Comment by SchwererKonigstiger** [comment]
War Mission related tickets closed temporarily. 
Will see what we can do next regarding it crashing.
